

/***************************** Include Files *******************************/
#include "FreqCounter.h"

/************************** Function Definitions ***************************/
/* PWL this is where we should write the drivers
 * according to Roy's Project 2 specification we need functions to:
 *		Initialize the peripheral to the correct mode (we probably don't need this)
 *		Capture a frequency reading
 *		Convert count reading to scaled voltage
 *			corresponding to the average voltage
 *			applied to the LED
 * 		Adjust scaling factors based on actual operation
 * 			of our circuit (characterize the circuit)
 */
 
 u32 FreqCounter_BaseAddr;	// global to the driver base address of this device
							// This address is generated by Vivado when we use
							// the IP block Diagram tool. It is passed to the main
							// software program via the xparamaters.h file
							// We expect the address to be passed into here when the 
							// peripheral is initialized (and we then store it
							// in this variable)
							
 FreqCounterReg MyFreqCtr = FreqCounter_BaseAddr						
//TODO: Currently only the header file has the nice comments for these functions
// you should probably get them moved in here too!!!

XStatus FREQCOUNTER_Initialize(u32 BaseAddr);
{	
	FreqCounter_BaseAddr = BaseAddr; //Populate the global variable
	return FREQCOUNTER_Reg_SelfTest(FreqCounter_BaseAddr);
}

void FREQCOUNTER_Get Counts(u32 BaseAddr, u32* HighCount, u32* LowCount)
{
	*Highcount = FREQCOUNTER_mReadReg(BaseAddr, MyFreqCtr->highCountReg);
	*LowCount  = FREQCOUNTER_mReadReg(BaseAddr, MyFreqCtr->lowCountReg);
}


// TODO: write FREQCOUNTER_CountsToVolts
// TODO: write FREQCOUNTER_ScaleCounts






