# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a100tcsg324-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir c:/users/paul/dropbox/1-ece544/projects/ip_repo/freqcounter_1.0/freqcounter_v1_0_v1_0_project/FreqCounter_v1_0_v1_0_project.cache/wt [current_project]
set_property parent.project_path c:/users/paul/dropbox/1-ece544/projects/ip_repo/freqcounter_1.0/freqcounter_v1_0_v1_0_project/FreqCounter_v1_0_v1_0_project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths C:/Users/Paul/Dropbox/1-ECE544/Projects/ip_repo/FreqCounter_1.0 [current_project]
read_verilog -library xil_defaultlib {
  c:/users/paul/dropbox/1-ece544/projects/ip_repo/freqcounter_1.0/freqcounter_v1_0_v1_0_project/FreqCounter_v1_0_v1_0_project.srcs/sources_1/imports/new/pw_det.v
  c:/users/paul/dropbox/1-ece544/projects/ip_repo/freqcounter_1.0/hdl/FreqCounter_v1_0_S00_AXI.v
  c:/users/paul/dropbox/1-ece544/projects/ip_repo/freqcounter_1.0/hdl/FreqCounter_v1_0.v
}
catch { write_hwdef -file FreqCounter_v1_0.hwdef }
synth_design -top FreqCounter_v1_0 -part xc7a100tcsg324-1
write_checkpoint -noxdef FreqCounter_v1_0.dcp
catch { report_utilization -file FreqCounter_v1_0_utilization_synth.rpt -pb FreqCounter_v1_0_utilization_synth.pb }
